# Generated by Django 5.0.6 on 2024-05-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="id пользователя в тг",
            ),
        ),
    ]
